version: "3.8"
services:
  # Customers Service
  customers_service:
    build:
      context: ./customers_service
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:Talineslim0303$@host.docker.internal:5432/customers_service
    networks:
      - ecommerce_network

  # Inventory Service
  inventory_service:
    build:
      context: ./inventory_service
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:Talineslim0303$@host.docker.internal:5432/inventory_service
    networks:
      - ecommerce_network

  # Review Service
  review_service:
    build:
      context: ./review_service
    ports:
      - "5003:5003"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:Talineslim0303$@host.docker.internal:5432/reviews_service
    networks:
      - ecommerce_network

  # Sales Service
  sales_service:
    build:
      context: ./sales_service
    ports:
      - "5004:5004"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:Talineslim0303$@host.docker.internal:5432/sales_service
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge
